version: '3'
services:
  timelock-web:
    build: .
    ports:
      - "8404:80"
    depends_on:
      - timevault-api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  timevault-api:
    build: ./api
    volumes:
      - vault-data:/data/uploads
    environment:
      - DATA_DIR=/data/uploads

volumes:
  vault-data:
